// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGa4ITl6qnmJKKl-kRqlX7bDnRXAlppOA',
    appId: '1:172883506469:web:9039ea3379539e842c56cc',
    messagingSenderId: '172883506469',
    projectId: 'ebook-f626f',
    authDomain: 'ebook-f626f.firebaseapp.com',
    storageBucket: 'ebook-f626f.firebasestorage.app',
    measurementId: 'G-Y0JRKTB8VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9iskhItOJMlRN8fT68xZmOcFj8UK9o9g',
    appId: '1:172883506469:android:5a00b6b335a4c9b22c56cc',
    messagingSenderId: '172883506469',
    projectId: 'ebook-f626f',
    storageBucket: 'ebook-f626f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWBdZAIdfvkpbPsIUnpqI66rSkOwYAlDc',
    appId: '1:172883506469:ios:7805915fed952f7b2c56cc',
    messagingSenderId: '172883506469',
    projectId: 'ebook-f626f',
    storageBucket: 'ebook-f626f.firebasestorage.app',
    androidClientId: '172883506469-d460484ridrklldvmja9oe20ocolcpil.apps.googleusercontent.com',
    iosClientId: '172883506469-bma1j8l9rj9tfk4nncnulke5dsp1faeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.itds283Sec2Group7CodeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWBdZAIdfvkpbPsIUnpqI66rSkOwYAlDc',
    appId: '1:172883506469:ios:7805915fed952f7b2c56cc',
    messagingSenderId: '172883506469',
    projectId: 'ebook-f626f',
    storageBucket: 'ebook-f626f.firebasestorage.app',
    androidClientId: '172883506469-d460484ridrklldvmja9oe20ocolcpil.apps.googleusercontent.com',
    iosClientId: '172883506469-bma1j8l9rj9tfk4nncnulke5dsp1faeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.itds283Sec2Group7CodeMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGa4ITl6qnmJKKl-kRqlX7bDnRXAlppOA',
    appId: '1:172883506469:web:2efc027dc4ee70032c56cc',
    messagingSenderId: '172883506469',
    projectId: 'ebook-f626f',
    authDomain: 'ebook-f626f.firebaseapp.com',
    storageBucket: 'ebook-f626f.firebasestorage.app',
    measurementId: 'G-PHBL9N5P9Y',
  );
}
